### ISSUE TITLE
wrong password found

### ISSUE THREAD

**Issue by kolet** [r3nt0n/keepass4brute#3] opened 2023-04-02 10:23 UTC
hey , i've made a dic , and the first pw of the list said it was the password but it wasnt .

**Comment by r3nt0n** [comment] 2023-04-03 17:52
Hello!

Im not being able to reproduce the issue, could you provide more details? As I need to know the word that is causing a false positive, if you are using a personal KeePass database and dont want to share any sensitive info, please create a kdbx and a wordlist for testing purposes. See if you can reproduce the issue and share with me the wordlist.

Thank you

**Comment by r3nt0n** [comment] 2023-04-09 19:20
I updated keepassxc-cli to version 2.7.4 and still can't reproduce the issue, no matter what wordlist or kpdb I use, I cannot generate any false positive.

@zorddy @kolet could you please paste the output of the tool and maybe the testing files you are using? 

Thank you for your help

**Comment by r3nt0n** [comment] 2023-04-28 07:06
Thanks @zorddy !

I still couldn't reproduce the issue using your files:

![image](https://user-images.githubusercontent.com/25709767/235078012-69f7a89d-7a59-433f-9e58-14dae3f2d5fc.png)

Can you think of any other thing that may differ between our environments?

**Comment by r3nt0n** [comment] 2023-05-25 12:28
Thanks, nice catch @marvinxyz !! I have changed the way that the script detects successful passwords by taking the return value instead of grep for a word to make it language independent, it should be fixed with the last commit.

Thank you guys @kolet and @zorddy for the report and help. I'm closing the issue, if you test it and still detect something odd, feel free to comment here.

**Closed by r3nt0n** 2023-05-25 12:28 UTC
